### PR TITLE
[DS-1471] Move back fix for redirect to avoid redirecting for cached cripts and styles

### PR DESCRIPTION
**Pull request by aleevas**
Fix for https://github.com/open-y-subprojects/openy_custom/pull/74 and https://github.com/open-y-subprojects/openy_custom/pull/73

Steps to reproduce you can find here https://github.com/open-y-subprojects/openy_custom/pull/73#issue-2330547080

### CODE REVIEW

**Comment by froboy** [comment]
@aleevas this looks better, but can you help me understand why we need to do this in addition to doing it in the [redirect module](https://www.drupal.org/project/redirect/issues/3373123)? Can't we just add that as a patch, or is this resolving the same issue in a different place?

**Comment by aleevas** [comment]
> @aleevas this looks better, but can you help me understand why we need to do this in addition to doing it in the [redirect module](https://www.drupal.org/project/redirect/issues/3373123)? Can't we just add that as a patch, or is this resolving the same issue in a different place?
@froboy 
Yes, it might work as a patch to redirect the module, but I didn't check this way. Anyway, it works and is much simpler to test. We could remove this RouteSibscriber when the redirect module is finally released.

**Comment by froboy** [comment]
@aleevas I don't trust us to remember to remove the code, and I'd rather not duplicate code if we can help it.

Can we just add this patch to [yusaopeny/composer.json](https://github.com/YCloudYUSA/yusaopeny/blob/main/composer.json)?

```
                "drupal/redirect": {
                    "https://dgo.to/3373123 Setting 'Enforce clean and canonical URLs.' breaks CSS aggregation on multilingual Drupal 10.1.x with browser caching enabled": "https://git.drupalcode.org/project/redirect/-/merge_requests/93.patch"
                }

**Comment by aleevas** [comment]
> @aleevas I don't trust us to remember to remove the code, and I'd rather not duplicate code if we can help it.
> 
> Can we just add this patch to [yusaopeny/composer.json](https://github.com/YCloudYUSA/yusaopeny/blob/main/composer.json)?
> 
> ```
>                 "drupal/redirect": {
>                     "https://dgo.to/3373123 Setting 'Enforce clean and canonical URLs.' breaks CSS aggregation on multilingual Drupal 10.1.x with browser caching enabled": "https://git.drupalcode.org/project/redirect/-/merge_requests/93.patch"
>                 }
> ```

@froboy 
This PR was updated - 0bbf3b094ce44e0b308089bd12891510346c3f7e
The patch is here https://github.com/YCloudYUSA/yusaopeny/pull/193/files

**Comment by froboy** [comment]
Thank you! Once that is merged this can be closed as unneeded. I appreciate the conversation.

**Review by podarok — APPROVED** [review]

**Pull request merged**
